### ISSUE TITLE
Sample project doesn't work with Mac OS 10.11 and Xcode 7.0.1

### ISSUE THREAD

**Issue by edwardloveall** [ofnode/ofxShivaVG#2]
Cloning this repo and opening the sample project gives these errors:
![xcode 7 0 1 errors](https://cloud.githubusercontent.com/assets/49549/10468901/b4a1f96e-71cf-11e5-96b7-cce03b38df3f.png)

I'm new to oF but I'll happily try any suggestions.

**Comment by procedural** [comment]
Could you add `#include "ofAppGLFWWindow.h"` on top of the file and see if it helps?

**Comment by edwardloveall** [comment]
Looks like that got rid of one error, but most still remain:
![errors](https://cloud.githubusercontent.com/assets/49549/10469823/758bec6a-71d6-11e5-86b1-15658d01dd84.png)

**Comment by procedural** [comment]
Oh, you must be using xcode project which's in directory of this project? I tested it only on CMake-based openFrameworks, don't know how to update current xcode project manually. You can try to get some project from official openFrameworks examples folder and adapt it to the example of this repo...

**Comment by procedural** [comment]
These errors are thrown because this fork doesn't support OF 0.8.4 anymore, please use 0.9.0 for it and open an issue if you'll have problems with it!
